#List of unicode characters for the user to print 
inverted_exclamation = u"\u00A1"
cent_sign = u"\u00A2"
pound_sign = u"\u00A3"
currency_sign = u"\u00A4"
yen_sign = u"\u00A5"
broken_bar = u"\u00A6"
section_sign = u"\u00A7"
umlaut = u"\u00a8"
copyright_sign = u"\u00a9"
ordinal_a = u"\u00aa"
left_double_arrow = u"\u00ab"
formal_negation_symbol = u"\u00ac"
blank_space = u"\u00ad"
registered = u"\u00ae"
top_underscore = u"\u00af"
hollow_bullet_point = u"\u00b0"
plus_minus_sign = u"\u00b1"
superscript_2 = u"\u00b2"
superscript_3 = u"\u00b3"
accent_mark = u"\u00b4"
mu = u"\u00b5"
space_symbol = u"\u00b6"
center_dot = u"\u00b7"
curly_comma = u"\u00b8"
superscript_1 = "\u00b9"
superscipt_0 = u"\u00ba"
right_double_arrow = u"\u00bb"
one_fourth = u"\u00bc"
one_half = u"\u00bd"
three_fourths = u"\u00be"
inverted_question = u"\u00bf"
left_accent_a = u"\u00c0"
right_accent_a = u"\u00c1"
circumflex_a = u"\u00c2"
tilda_a = u"\u00c3"
umlaut_a = u"\u00c4"
overdot_a = u"\u00c5"
ae_compound = u"\u00c6"
undercomma_c = u"\u00c7"
left_accent_e = u"\u00c8"
right_accent_e = u"\u00c9"
circumflex_e = u"\u00ca"
umlaut_e = u"\u00cb"
left_accent_i = u"\u00cc"
right_accent_i = u"\u00cd"
circumflex_i = u"\u00ce"
umlaut_i = u"\u00cf"
eth = u"\u00d0"
tilda_n = u"\u00d1"
left_accent_o = u"\u00d2"
right_accent_o = u"\u00d3"
circumflex_o = u"\u00d4"
tilda_o = u"\u00d5"
umlaut_o = u"\u00d6"
multiplication = u"\u00d7"
slashed_o = u"\u00d8"
left_accent_u = u"\u00d9"
right_accent_u = u"\u00da"
circumflex_u = u"\u00db"
umlaut_u = u"\u00dc"
right_accent_y = u"\u00dd"
thorn = u"\u00de"
double_s = u"\u00df"
left_accent_a_lowercase = u"\u00e0"
right_accent_a_lowercase = u"\u00e1"
circumflex_a_lowercase = u"\u00e2"
tilda_a_lowercase = u"\u00e3"
umlaut_a_lowercase = u"\u00e4"
overdot_a_lowercase = u"\u00e5"
ae_compound_lowercase = u"\u00e6"
undercomma_c_lowercase = u"\u00e7"
left_accent_e_lowercase = u"\u00e8"
right_accent_e_lowercase = u"\u00e9"
circumflex_e_lowercase = u"\u00ea"
umlaut_e_lowercase = u"\u00eb"
left_accent_i_lowercase = u"\u00ec"
right_accent_i_lowecase = u"\u00ed"
circumflex_i_lowercase = u"\u00ee"
umlaut_i_lowercase = u"\u00ef"
eth_lowercase = u"\u00f0"
tilda_n = u"\u00f1"
left_accent_o_lowercase = u"\u00f2"
right_accent_o_lowercase = u"\u00f3"
circumflex_o_lowercase = u"\u00f4"
tilda_o_lowercase = u"\u00f5"
umlaut_o_lowercase = u"\u00f6"
division_sign = u"\u00f7"
slashed_o_lowercase = u"\u00f8"
left_accent_u_lowercase u"\u00f9"
right_accent_u_lowercase = u"\u00fa"
circumflex_u_lowercase = u"\u00fb"
umlaut_u_lowercase = u"\u00fc"
right_accent_y_lowercase = u"\u00fd"
thorn_lowercase = u"\u00fe"
umlaut_y_lowercase = u"\u00ff"
    




def help():
    print("Syntax: print typewrite.(symbol).\n Please refer to the README for full list of characters.")



    